# Generated by Django 4.2 on 2023-05-07 07:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='weather_type',
            field=models.CharField(choices=[('cloudy', 'Cloudy'), ('windy', 'Windy'), ('rainy', 'Rainy'), ('stormy', 'Stormy')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='temperature',
            field=models.FloatField(validators=[django.core.validators.MinLengthValidator(-90.0), django.core.validators.MaxLengthValidator(60.0)]),
        ),
    ]
