# Generated by Django 4.2 on 2023-05-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_share', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imges_uploaded',
            field=models.IntegerField(default=0),
        ),
    ]
