# Generated by Django 4.2 on 2023-05-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
