# Generated by Django 4.2 on 2023-04-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gif_app', '0002_alter_category_model_gifs_alter_category_model_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_model',
            name='gifs',
            field=models.ManyToManyField(blank=True, related_name='categories', to='gif_app.gif_model'),
        ),
    ]
